version: '3'

services:
  fiji:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $GUIPORT:8080
    volumes:
      - $HOME_RESEARCHER:/data # change the path before ":" with the volume you want to mount
    working_dir: /data
    container_name: $COMPOSE_PROJECT_NAME
    hostname: $HOST_NAME
    user: root
    environment:
       - GUIPORT=${GUIPORT}
       - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
       - HOST_NAME=${HOST_NAME}
       - HOME_RESEARCHER=${HOME_RESEARCHER}