version: '3'

services:
  slicer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $GUIPORT:8080
      - $JLPORT:8888
    volumes:
      - $HOME_RESEARCHER:/home/researcher/mounted_volume # change the path before ":" with the volume you want to mount
    working_dir: /home/researcher/mounted_volume
    container_name: $COMPOSE_PROJECT_NAME
    hostname: $HOST_NAME
    user: root
    environment:
       - GUIPORT=${GUIPORT}
       - JLPORT=${JLPORT}
       - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
       - HOST_NAME=${HOST_NAME}
       - HOME_RESEARCHER=${HOME_RESEARCHER}