version: '3'

services:
  flowcyto:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RES_UID: ${RES_UID:-0}
        RES_GID: ${RES_GID:-0}
    ports:
      - 7777:7777
      - $RSPORT:7878
    volumes:
      - $HOME_RESEARCHER:/home/researcher # change the path before ":" with the volume you want to mount
    working_dir: /home/researcher
    container_name: $COMPOSE_PROJECT_NAME
    hostname: $HOST_NAME
    user: root
    environment:
       - RSPORT=${RSPORT}
       - USER_RESEARCHER=${USER_RESEARCHER}
       - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
       - HOST_NAME=${HOST_NAME}
       - HOME_RESEARCHER=${HOME_RESEARCHER}