version: '3'

services:
  image3d:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RES_UID: ${RES_UID:-0}
        RES_GID: ${RES_GID:-0}
    ports:
      - $JUPYTERPORT:$JUPYTERPORT
    volumes:
      - $HOME_RESEARCHER:/home/sliceruser/work # change the path before ":" with the volume you want to mount
    working_dir: /home/sliceruser/work
    container_name: $COMPOSE_PROJECT_NAME
    user: root
    hostname: $HOST_NAME
    environment:
       - JUPYTERPORT=${JUPYTERPORT}
       - USER_RESEARCHER=${USER_RESEARCHER}
       - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
       - HOST_NAME=${HOST_NAME}
       - HOME_RESEARCHER=${HOME_RESEARCHER}