---
version: "3"
services:
  sc-r-env:
    image: gnasello/sc-r-env:latest
    container_name: $COMPOSE_PROJECT_NAME
    volumes:
      - $HOME_RESEARCHER:/home/jovyan/researcher_home
    #working_dir: /home/researcher/
    ports:
      - $JLPORT:$JLPORT
    user: root
    hostname: $HOST_NAME
    environment:
      #- NB_USER=researcher
      - NB_UID=$RES_UID
      - NB_GID=$RES_GID
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - GRANT_SUDO=yes
      - JUPYTER_PORT=${JLPORT}
      - JLPORT=${JLPORT}
      - HOST_NAME=${HOST_NAME}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - HOME_RESEARCHER=${HOME_RESEARCHER}
      - RES_UID=${RES_UID}
      - RES_GID=${RES_GID}